teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1  # forward/back
    axis_angular:
      yaw: 2  # Twist
    scale_linear:
      x: 1.0
    scale_angular:
      yaw: 1.0

    deadzone: 0.5

    # enable_button: 4
    # enable_turbo_button: 5

    deadzone: 0.3
    
    require_enable_button: false
