controller_manager:
  ros__parameters:
    update_rate: 50 # This is in Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tibble_controller:
      type: "tibble_controller/TibbleController"

tibble_controller:
  ros__parameters:
    wheel_radius_m: 0.929      # allegedly correct 929 mm
    wheel_separation_m: 0.5659  # allegedly correct 5659 mm

    excavate_speed_multiplier: 0.5
    # paddle_speed: 6.28318530718 # 2pi
    # manual_paddle_max_speed: 6.28318530718
    paddle_speed: 12.25
    manual_paddle_max_speed: 12.25
    manual_la_speed: 0.01

    # technically not used anywhere
    odom_topic: "/odom"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_odom_tf: true