controller_manager:
  ros__parameters:
    update_rate: 100 # This is in Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tibble_controller:
      type: "tibble_controller/TibbleController"

tibble_controller:
  ros__parameters:
    wheel_radius_m: 0.15      # placeholder
    wheel_separation_m: 0.60  # placeholder

    excavate_speed_multiplier: 0.5
    paddle_speed: 1 # placeholder

    # technically not used anywhere
    odom_topic: "/odom"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_odom_tf: true
