controller_manager:
  ros__parameters:
    update_rate: 50 # This is in Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tibble_controller:
      type: "tibble_controller/TibbleController"

tibble_controller:
  ros__parameters:

    left_wheel_names:
      - ML_Wheel_Rotate

    right_wheel_names:
      - MR_Wheel_Rotate

    drive_gear_radius: 0.048928525 # allegedly correct 48.928525 mm
    wheel_radius_m: 0.076835      # allegedly correct 76.835 mm 
    wheel_separation_m: 0.5659  # allegedly correct 5659 mm

    excavate_speed_multiplier: 0.5
    paddle_speed: 6.28318530718 # 2pi

    # technically not used anywhere
    odom_topic: "/odom"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_odom_tf: true
