# TODO: Configure program to emit cmd_vel in this arrangement (itll be terrible)
twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : nav_cmd_vel
        timeout : 0.5
        priority: 10
      joystick:
        topic   : joy_cmd_vel
        timeout : 0.5
        priority: 100 